server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Luvio?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: